name: ⚡ Clean Windows RDP

on:
  workflow_dispatch:
    inputs:
      CODE:
        description: "Paste CRD command from remotedesktop.google.com/headless"
        required: true
      PIN:
        description: "6+ digit PIN"
        required: true
        default: "123456"

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 🧰 Setup Chrome Remote Desktop
        run: |
          Write-Host "Downloading Chrome Remote Desktop..."
          Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile crd.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/i crd.msi /quiet /norestart'

      - name: 🚀 Start Remote Desktop
        run: |
          $code = "${{ github.event.inputs.CODE }}"
          $pin = "${{ github.event.inputs.PIN }}"

          Write-Host "Starting Chrome Remote Desktop..."

          cmd.exe /c "$code --pin=$pin"

      - name: ⏳ Keep Alive
        run: |
          Write-Host "Machine is running..."
          for ($i=0; $i -lt 360; $i++) {
            Start-Sleep -Seconds 60
          }
