name: ⚡ Clean RDP Working

on:
  workflow_dispatch:
    inputs:
      CODE:
        description: "Paste CRD command"
        required: true
      PIN:
        description: "PIN"
        required: true
        default: "123456"

jobs:
  rdp:
    runs-on: windows-2022

    steps:
      - name: Install Chrome Remote Desktop
        run: |
          Invoke-WebRequest https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi -OutFile crd.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/i crd.msi /quiet /norestart'

      - name: Start CRD
        run: |
          $code = "${{ github.event.inputs.CODE }}"
          $pin = "${{ github.event.inputs.PIN }}"

          cmd /c "$code --pin=$pin"

      - name: Keep Alive
        run: |
          for ($i=0; $i -lt 300; $i++) {
            Start-Sleep -Seconds 60
          }
